name: "Fungal_Networks"
output_dir: "docs"
navbar:
  title: "Fungal Networks"
  left:
  - text: "Home"
   href: Multivariate.html
  - text: "Analysis with Igraph"
   href: analysis_igraph.html
output:
  html_document:
theme: jekyll-theme-cayman